connector.name=iceberg

iceberg.catalog.type=hive_metastore
hive.metastore.uri=thrift://hive-metastore:9083

fs.hadoop.enabled=true

hive.config.resources=/etc/hadoop/conf/core-site.xml

iceberg.file-format=PARQUET
iceberg.compression-codec=ZSTD
iceberg.unique-table-location=true
