connector.name=postgresql

connection-url=jdbc:postgresql://datalake:5432/BigData
connection-user=postgres
connection-password=postgres

case-insensitive-name-matching=true
metadata.cache-ttl=5m